apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fluentd.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "fluentd.fullname" . }}
    spec:
      serviceAccountName: {{ template "fluentd.fullname" . }}
      initContainers:
      - name: wait-for-syslog
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - sh
        - -c
        - until nc -v -w5 -z {{ template "syslog.fullname" . }} 601 ; do sleep 5; done
      containers:
      - name: fluentd
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SYSLOG_HOST
          value: "{{ template "syslog.fullname" . }}"
        - name: SYSLOG_PORT
          value: "514"
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          readOnly: true
          mountPath: /var/lib/docker/containers
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "fluentd.fullname" . }}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
