apiVersion: v1
kind: Service
metadata:
  name: {{ template "syslog.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "syslog.fullname" . }}
spec:
  ports:
    - port: 514
      name: udp
      protocol: UDP
    - port: 601
      name: tcp
      protocol: TCP
  selector:
    app: {{ template "syslog.fullname" . }}
  type: ClusterIP
