apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shellinabox.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "shellinabox.fullname" . }}
data:
  command.sh: |
    #!/bin/sh

    stern --kubeconfig /root/.kube/config -l app={{ template "shellinabox-logs.fullname" . }} | awk '{$1=$2=""; print $0}'