{{- if .Values.rbac.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "shellinabox.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "shellinabox.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "pods/log"
  verbs:
  - "get"
  - "watch"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "shellinabox.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "shellinabox.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "shellinabox.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "shellinabox.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}