apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lcm.fullname" . }}-scale-manual
data:
  scale.json: |
    {
      "application": "{{ .Values.spinnaker.application.name }}",
      "name": "Kubernetes manual scale",
      "appConfig": {},
      "keepWaitingPipelines": false,
      "lastModifiedBy": "anonymous",
      "limitConcurrent": true,
      "parallel": true,
      "parameterConfig": [
        {
          "description": "List of node IPs to add",
          "name": "NODES"
        },
        {
          "default": "false",
          "name": "DEBUG"
        }
      ],
      "stages": [
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cxe",
              "new=$(echo -n ${ parameters.NODES } | jq -rRMsc 'split(\",\")') && nodes=$(curl -kSs https://{{ template "lcm.apocng.fullname" . }}/api/store2/{{ .Values.envId }}/ | jq \".apocng_manual_nodes += $new\" | jq '.apocng_manual_nodes') && curl -d \"{\\\"apocng_manual_nodes\\\": $nodes}\" -k -f https://{{ template "lcm.apocng.fullname" . }}/api/store2/{{ .Values.envId }}/"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "k8sprayorg",
              "registry": "index.docker.io",
              "repository": "k8sprayorg/ansible",
              "tag": "2.3.0.0"
            },
            "name": "k8spray",
            "volumeMounts": []
          },
          "labels": {
            "envId": "{{ .Values.envId }}"
          },
          "name": "Prepare config",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "1",
          "requisiteStageRefIds": [],
          "type": "runJob",
          "volumeSources": []
        },
        {
          "application": "{{ .Values.spinnaker.application.name }}",
          "failPipeline": true,
          "name": "Scale Kubernetes",
          "pipeline": "${SCALE_PIPELINE_ID}",
          "refId": "2",
          "requisiteStageRefIds": [
            "1"
          ],
          "type": "pipeline",
          "waitForCompletion": true
        }
      ],
      "triggers": []
    }