apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shellinabox.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "shellinabox.fullname" . }}
data:
  command.sh: |
    #!/bin/sh

    syslog_pod=$(kubectl get pods -l app=syslog-k8spray -o jsonpath='{.items[*].metadata.name}')
    kubectl --context default --kubeconfig /root/.kube/config logs -f $syslog_pod | perl -nle 'print $& if m{^k8spray-{{ .Values.envId }}\K.*}'