apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lcm.fullname" . }}-install
data:
  install.json: |
    {
      "application": "{{ .Values.spinnaker.application.name }}",
      "name": "Kubernetes install",
      "appConfig": {},
      "keepWaitingPipelines": false,
      "lastModifiedBy": "anonymous",
      "limitConcurrent": true,
      "parallel": true,
      "parameterConfig": [
        {
          "name": "ENV_ID"
        }
      ],
      "stages": [
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cex",
              "ANSIBLE_CONFIG=/opt/playbooks/workflow/ansible.cfg ansible-playbook -e env_id=\"${ parameters.ENV_ID }\" /opt/playbooks/workflow/prepare.yml"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "k8sprayorg",
              "registry": "index.docker.io",
              "repository": "k8sprayorg/ansible",
              "tag": "2.3.0.0"
            },
            "name": "job",
            "volumeMounts": []
          },
          "labels": {},
          "name": "Prepare nodes",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "3",
          "requisiteStageRefIds": [],
          "type": "runJob",
          "volumeSources": []
        },
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cex",
              "export ANSIBLE_CONFIG=/opt/playbooks/workflow/ansible.cfg && ansible-playbook -e env_id=\"${ parameters.ENV_ID }\" /opt/playbooks/workflow/deployment.yml && ansible-playbook -i /tmp/inventory.cfg -e@/tmp/${ parameters.ENV_ID }-kubespray-values /opt/playbooks/kubespray/cluster.yml --become"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "k8sprayorg",
              "registry": "index.docker.io",
              "repository": "k8sprayorg/ansible",
              "tag": "2.3.0.0"
            },
            "name": "job",
            "volumeMounts": []
          },
          "labels": {},
          "name": "Deploy Kubernetes",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "4",
          "requisiteStageRefIds": [
            "3"
          ],
          "type": "runJob",
          "volumeSources": []
        },
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cex",
              "ANSIBLE_CONFIG=/opt/playbooks/workflow/ansible.cfg ansible-playbook -e env_id=\"${ parameters.ENV_ID }\" /opt/playbooks/workflow/configure.yml"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "k8sprayorg",
              "registry": "index.docker.io",
              "repository": "k8sprayorg/ansible",
              "tag": "2.3.0.0"
            },
            "name": "job",
            "volumeMounts": []
          },
          "labels": {},
          "name": "Configure Kubernetes",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "5",
          "requisiteStageRefIds": [
            "4"
          ],
          "type": "runJob",
          "volumeSources": []
        },
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cex",
              "ANSIBLE_CONFIG=/opt/playbooks/workflow/ansible.cfg ansible-playbook -e env_id=\"${ parameters.ENV_ID }\" /opt/playbooks/workflow/migrate.yml"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "k8sprayorg",
              "registry": "index.docker.io",
              "repository": "k8sprayorg/ansible",
              "tag": "2.3.0.0"
            },
            "name": "job",
            "volumeMounts": []
          },
          "labels": {},
          "name": "Migrate lcm",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "6",
          "requisiteStageRefIds": [
            "5"
          ],
          "type": "runJob",
          "volumeSources": []
        }
      ],
      "triggers": []
    }