apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-igor
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: igor
spec:
  ports:
    - port: 8088
      name: igor
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: igor
