apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lcm.fullname" . }}-scale
data:
  scale.json: |
    {
      "application": "{{ .Values.spinnaker.application.name }}",
      "name": "Kubernetes scale",
      "appConfig": {},
      "keepWaitingPipelines": false,
      "lastModifiedBy": "anonymous",
      "limitConcurrent": true,
      "parallel": true,
      "parameterConfig": [],
      "stages": [
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cex",
              "export ANSIBLE_CONFIG=/opt/playbooks/workflow/ansible.cfg && ansible-playbook -e env_id=\"{{ .Values.envId }}\" /opt/playbooks/workflow/scale.yml && ansible-playbook -i /tmp/inventory.cfg -e@/tmp/{{ .Values.envId }}-kubespray-values /opt/playbooks/kubespray/scale.yml --become"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "k8sprayorg",
              "registry": "index.docker.io",
              "repository": "k8sprayorg/ansible",
              "tag": "2.3.0.0"
            },
            "name": "k8spray-{{ .Values.envId }}",
            "volumeMounts": []
          },
          "labels": {
            "envId": "{{ .Values.envId }}"
          },
          "name": "Scale Kubernetes",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "1",
          "type": "runJob",
          "volumeSources": []
        }
      ],
      "triggers": []
    }